export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_BTN_LARGE = 'SET_BTN_LARGE';

export const ADD_A_OUTPUT = 'ADD_A_OUTPUT';
export const REMOVE_A_OUTPUT = 'REMOVE_A_OUTPUT';
export const ADD_OUTPUT_NAME = 'ADD_OUTPUT_NAME';
export const REMOVE_OUTPUT_NAME = 'REMOVE_OUTPUT_NAME';

export const SET_FORM_DATA = 'SET_FORM_DATA';
export const SET_OUTPUT_FORM_DATA = 'SET_OUTPUT_FORM_DATA';

export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';
export const SET_FROM_SUBMIT_SUCCESS = 'SET_FROM_SUBMIT_SUCCESS';

export const CLOSE_POPUP = 'CLOSE_POPUP';
